spring.application.name=survivalg
server.port=8080
spring.thymeleaf.enabled=true
logging.level.root=INFO

# Hibernate and JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

# H2 Database Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./survivalg-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Logging
logging.level.org.hibernate=WARN
logging.level.org.hibernate.orm.core=WARN

# Admin Configuration
admin.username=admin
admin.password=survival2026

game.domain.name=stalkzona.online